version: '3.8'
services:
  warband-ni:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fianna_ni_server
    ports:
      - "7240:7240/udp"
      - "7241:7241/udp"
    volumes:
      - ./Modules/Fianna_NordInvasion:/home/warband/server/Modules/Fianna_NordInvasion
      - ./nordinvasion.cfg:/home/warband/server/nordinvasion.cfg
      - ./logs:/home/warband/server/logs
    restart: unless-stopped
    stdin_open: true
    tty: true
